baseurl = "/"
title = "Rose Hugo"
defaultContentLanguage = 'zh-cn'
theme = "rose-hugo"

summaryLength = 3
ignoreLogs = ['warning-goldmark-raw-html']

[pagination]
  pagerSize = 10

[permalinks]
  posts="/posts/:year/:month/:day/:slug/"
  categories="/categories/:slug/"
  tags="/tags/:slug/"
  pages="/:slug/"

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 5

[Params]
  author = "rose"
  avatar = "/image/avatar.jpg"
  logo = "/image/logo.svg" # Logo image
  subtitle = "Just another hugo theme" # Logo subtitle
  description = "A Personal blog about everything" # Description of your site
  authorbox = true # Show authorbox at bottom of pages if true
  authorIntro = "A developer from China Wuhan, mostly writing about software development and open-source. <br> Browse my [blog posts](/posts), subscribe to my [RSS feed](/index.xml), or learn more [about me](/about/)."
  toc = false # Enable Table of Contents
  post_meta = [ "date", "categories", "author", "translations"] # Order of post meta information
  mainSections = ["posts"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = false # Enable MathJax
  mathjaxPath = "https://cdn.jsdmirror.com/npm/mathjax@2.7.9/MathJax.min.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  mermaid="https://cdn.jsdmirror.com/npm/mermaid@11.8.0/dist/mermaid.min.js"

#[Params.sidebar]
#  home = "right" # Position of sidebar on home page: "left", "right", "none"
  # Enable widgets in given order: "search", "recent", "categories", "taglist", "languages"
#  widgets = ["search", "recent", "categories", "taglist"]

[Params.thumbnail]
  # Control thumbnail visibility, eg: list、post
  visibility = ["list"]

[Params.widgets.social]
  cached = false # activate cache if true
  facebook = "username"
  twitter = "username"
  instagram = "username"
  linkedin = "username"
  telegram = "username"
  github = "username"
  gitlab = "username"
  bitbucket = "username"
  email = "username@gmail.com"
  youtube = "username"

[Params.style]
  highlightColor = "#e22d30"
  fontFamilyPrimary = '"Open Sans", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "WenQuanYi Micro Hei", Helvetica, Arial, sans-serif'
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
