name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - '20.x'

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:css

  test-hugo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hugo:
          - '0.132.2'
          - 'latest'
      fail-fast: true

    steps:
      - uses: actions/checkout@v5

      - name: Run Hugo ${{ matrix.hugo }}
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ matrix.hugo }}
          # extended: true

      - name: Build with Hugo ${{ matrix.hugo }}
        working-directory: exampleSite
        run: |
          hugo --themesDir ../..
